apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData:
  user-manager-db-url: "postgresql://user_manager:password@user-db:5432/user_manager_db"
  data-collector-db-url: "postgresql://data_collector:password@data-db:5432/data_collector_db"
---
apiVersion: v1
kind: Secret
metadata:
  name: opensky-secrets
type: Opaque
stringData:
  client-id: "your_client_id"
  client-secret: "your_client_secret"