apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData:
  user-manager-db-url: "postgresql://user_manager:password@user-db:5432/user_manager_db"
  data-collector-db-url: "postgresql://data_collector:password@data-db:5432/data_collector_db"
---
apiVersion: v1
kind: Secret
metadata:
  name: opensky-secrets
type: Opaque
stringData:
  client-id: your-client-id
  client-secret: your-client-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: telegram-secrets
type: Opaque
stringData:
  telegram-token: your-telegram-token